apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: Kafka-Cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      tls:
        authentication:
          type: tls  # use mTLS
      external:
        type: nodeport
        tls: true
        authentication:
          type: tls  # use mTLS
        overrides:
          brokers:  # set advertised.listener in Kafka
          - broker: 0
            advertisedHost: Kubectl-Server-Ip
          - broker: 1
            advertisedHost: Kubectl-Server-Ip
          - broker: 2
            advertisedHost: Kubectl-Server-Ip
    authorization:
      type: simple  # use Kafka's ACL plugin SimpleAclAuthorizer
      superUsers:  # ignore ACLs
        - CN=super-0
        - super-1
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:  # configure Operators for this cluster
    topicOperator: {}
    userOperator: {}
