apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: Kafka-Cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
#      tls:
#        authentication:
#          type: tls  # use mTLS
      external:
        type: nodeport
        tls: false
#        tls: true
#        authentication:
#          type: tls  # use mTLS
        overrides:
          bootstrap:
            nodePort: 31000
          brokers:  # set advertised.listener in Kafka
          - broker: 0
            advertisedHost: Kubectl-Server-Ip
          - broker: 1
            advertisedHost: Kubectl-Server-Ip
          - broker: 2
            advertisedHost: Kubectl-Server-Ip
#    authorization:
#      type: simple  # use Kafka's ACL plugin SimpleAclAuthorizer
#      superUsers:  # ignore ACLs
#        - CN=super-0
#        - super-1
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:  # configure Operators for this cluster
    topicOperator: {}
    userOperator: {}
