apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: User-Name  # change
  labels:
    strimzi.io/cluster: Kafka-Cluster  # change
  namespace: K8s-Strimzi-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  authentication:
    type: tls  # use mTLS
  authorization:
    type: simple  # use Kafka's ACL plugin SimpleAclAuthorizer
    acls:  # '*' is a wildcard
      - resource:
          type: topic
          name: Kafka-Topic
          patternType: literal
        operation: Read  # Consumer can Read
        host: "*"
      - resource:
          type: topic
          name: Kafka-Topic
          patternType: literal
        operation: Describe  # Consumer can Describe
        host: "*"
      - resource:
          type: group
          name: Consumer-Group-Name
          patternType: literal
        operation: Read  # Consumer can be a port of a Consumer Group
        host: "*"
      - resource:
          type: topic
          name: Kafka-Topic
          patternType: literal
        operation: Write  # Producer can Write
        host: "*"
      - resource:
          type: topic
          name: Kafka-Topic
          patternType: literal
        operation: Create  # Produer can Create
        host: "*"
      - resource:
          type: topic
          name: Kafka-Topic
          patternType: literal
        operation: Describe  # Producer can Describe
        host: "*"
