apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: simple-topic
  labels:
    strimzi.io/cluster: simple-strimzi
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour
